AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.1
  Exclude:
  - 'vendor/**/*'
  - 'yard/**/*'

Layout/IndentHeredoc:
  Enabled: false

# https://github.com/bbatsov/rubocop/pull/5230
Style/FormatStringToken:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false
