AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.5
  Exclude:
  - 'vendor/**/*'
  - 'yard/**/*'

Layout/IndentHeredoc:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

# The following are disabled until we drop support for the older ruby versions
Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/ClosingHeredocIndentation:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/SafeNavigation:
  Enabled: false
